import { seedCuratedCollections } from "./seedCuratedCollections";
import { seedHotArtists } from "./seedHotArtists";
import { seedSpotlight } from "./seedSpotlight";
import { seedNfts } from "./seedNfts";
import { seedTokenNfts } from "./seedTokenNfts";
import { seedProfileCollections } from "./seedProfileCollections";
import { seedActivityCollections } from "./seedActivityCollections";
import { seedCollectionsCreators } from "./seedCollectionsCreators";
import { seedFollowers } from "./seedFollowers";
import { seedFollowing } from "./seedFollowing";
import { seedDiscover } from "./seedDiscover";
import { seedCreators } from "./seedCreators";
import { seedCollectors } from "./seedCollectors";
import { seedActivities } from "./seedActivities";
import { seedArtists } from "./seedArtists";
import { seedArtistsWeek } from "./seedArtistsWeek";
import { seedAuctions } from "./seedAuctions";
import { seedBlog } from "./seedBlog";
import { seedBlogSlider } from "./seedBlogSlider";
import { seedHelp } from "./seedHelp";
import { seedHelpCategories } from "./seedHelpCategories";
import { seedHelpDetail } from "./seedHelpDetail";
import { seedBids } from "./seedBids";
import { seedStatistics } from "./seedStatistics";
import { seedLinks } from "./seedLinks";
import { seedProvenance } from "./seedProvenance";

export const seedAllTables = async () => {
  await seedHotArtists();
  await seedCuratedCollections();
  await seedSpotlight();
  await seedNfts();
  await seedTokenNfts();
  await seedProfileCollections();
  await seedActivityCollections();
  await seedCollectionsCreators();
  await seedFollowers();
  await seedFollowing();
  await seedDiscover();
  await seedCreators();
  await seedCollectors();
  await seedActivities();
  await seedArtists();
  await seedArtistsWeek();
  await seedAuctions();
  await seedBlog();
  await seedBlogSlider();
  await seedHelp();
  await seedHelpCategories();
  await seedHelpDetail();
  await seedBids();
  await seedStatistics();
  await seedLinks();
  await seedProvenance();
};
