import { Following } from "database/type";
import { seedTable } from "./seedTable";
import { following } from "database/schema";

const data: Following[] = [
  {
    id: 1,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-2.jpg",
    crypto: "4 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 2,
    name: "Moyo Shiro",
    login: "moyoshiro",
    avatar: "/images/artists/artist-3.jpg",
    crypto: "32 NFTs",
    follow: true,
    history: true,
    url: "/profile",
  },
  {
    id: 3,
    name: "Dash",
    login: "randomdash",
    avatar: "/images/artists/artist-1.jpg",
    crypto: "12 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 4,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-4.jpg",
    crypto: "60 NFTs",
    follow: true,
    history: true,
    url: "/profile",
  },
  {
    id: 5,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-5.jpg",
    crypto: "4 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 6,
    name: "Dash",
    login: "randomdash",
    avatar: "/images/artists/artist-1.jpg",
    crypto: "12 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 7,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-2.jpg",
    crypto: "4 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 8,
    name: "Moyo Shiro",
    login: "moyoshiro",
    avatar: "/images/artists/artist-3.jpg",
    crypto: "32 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 9,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-4.jpg",
    crypto: "60 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 10,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-5.jpg",
    crypto: "4 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 11,
    name: "Dash",
    login: "randomdash",
    avatar: "/images/artists/artist-1.jpg",
    crypto: "12 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 12,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-2.jpg",
    crypto: "4 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 13,
    name: "Moyo Shiro",
    login: "moyoshiro",
    avatar: "/images/artists/artist-3.jpg",
    crypto: "32 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 14,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-4.jpg",
    crypto: "60 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
  {
    id: 15,
    name: "Kohaku",
    login: "kohaku",
    avatar: "/images/artists/artist-5.jpg",
    crypto: "4 NFTs",
    follow: true,
    history: false,
    url: "/profile",
  },
];

export const seedFollowing = async () => {
  await seedTable(following, data, following.id);
};
