import { CuratedCollection } from "database/type";
import { seedTable } from "./seedTable";
import { curatedCollections } from "database/schema";

const data: CuratedCollection[] = [
  {
    id: 1,
    title: "Cute Planet",
    login: "tranmautritam",
    price: "1.0 ETH",
    avatar: "/images/artists/artist-1.jpg",
    images: [
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 2,
    title: "UI8 all-access",
    login: "randomdash",
    price: "1.2 ETH",
    avatar: "/images/artists/artist-2.jpg",
    images: [
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
    ],
    color: "#B9A9FB",
    url: "/collection",
  },
  {
    id: 3,
    title: "Beyond the Dream",
    login: "randomdash",
    price: "2.4 ETH",
    avatar: "/images/artists/artist-3.jpg",
    images: [
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
    ],
    color: "#DBFF73",
    url: "/collection",
  },
  {
    id: 4,
    title: "Beyond the Dream",
    login: "randomdash",
    price: "5.4 ETH",
    avatar: "/images/artists/artist-4.jpg",
    images: [
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
      "/images/collection/image-12.jpg",
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
      "/images/collection/image-12.jpg",
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 5,
    title: "Cute Planet",
    login: "tranmautritam",
    price: "1.0 ETH",
    avatar: "/images/artists/artist-1.jpg",
    images: [
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 6,
    title: "UI8 all-access",
    login: "randomdash",
    price: "1.2 ETH",
    avatar: "/images/artists/artist-2.jpg",
    images: [
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
    ],
    color: "#B9A9FB",
    url: "/collection",
  },
  {
    id: 7,
    title: "Beyond the Dream",
    login: "randomdash",
    price: "2.4 ETH",
    avatar: "/images/artists/artist-3.jpg",
    images: [
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
    ],
    color: "#DBFF73",
    url: "/collection",
  },
  {
    id: 8,
    title: "Beyond the Dream",
    login: "randomdash",
    price: "5.4 ETH",
    avatar: "/images/artists/artist-4.jpg",
    images: [
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
      "/images/collection/image-12.jpg",
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
      "/images/collection/image-12.jpg",
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 9,
    title: "Cute Planet",
    login: "tranmautritam",
    price: "1.0 ETH",
    avatar: "/images/artists/artist-1.jpg",
    images: [
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 10,
    title: "UI8 all-access",
    login: "randomdash",
    price: "1.2 ETH",
    avatar: "/images/artists/artist-2.jpg",
    images: [
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
      "/images/collection/image-6.jpg",
      "/images/collection/image-4.jpg",
      "/images/collection/image-5.jpg",
    ],
    color: "#B9A9FB",
    url: "/collection",
  },
  {
    id: 11,
    title: "Beyond the Dream",
    login: "randomdash",
    price: "2.4 ETH",
    avatar: "/images/artists/artist-3.jpg",
    images: [
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
      "/images/collection/image-7.jpg",
      "/images/collection/image-8.jpg",
      "/images/collection/image-9.jpg",
    ],
    color: "#DBFF73",
    url: "/collection",
  },
  {
    id: 12,
    title: "Beyond the Dream",
    login: "randomdash",
    price: "5.4 ETH",
    avatar: "/images/artists/artist-4.jpg",
    images: [
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
      "/images/collection/image-12.jpg",
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
      "/images/collection/image-12.jpg",
      "/images/collection/image-10.jpg",
      "/images/collection/image-11.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 13,
    title: "Cute Planet",
    login: "tranmautritam",
    price: "1.0 ETH",
    avatar: "/images/artists/artist-1.jpg",
    images: [
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
      "/images/collection/image-2.jpg",
      "/images/collection/image-3.jpg",
      "/images/collection/image-1.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
];

export const seedCuratedCollections = async () => {
  await seedTable(curatedCollections, data, curatedCollections.id);
};
