import { ArtistsWeek } from "database/type";
import { seedTable } from "./seedTable";
import { artistsWeek } from "database/schema";

const data: ArtistsWeek[] = [
  {
    id: 1,
    name: "Dash",
    avatar: "/images/artists/artist-1.jpg",
    sale: "5.244 ETH",
    crypto: "12 ETH",
    price: "$24,550",
    url: "/profile",
  },
  {
    id: 2,
    name: "Foxies",
    avatar: "/images/artists/artist-2.jpg",
    sale: "12.29 ETH",
    crypto: "5 ETH",
    price: "$15,000",
    url: "/profile",
  },
  {
    id: 3,
    name: "Kohaku",
    avatar: "/images/artists/artist-3.jpg",
    sale: "8.13 ETH",
    crypto: "3.2 ETH",
    price: "$9,344",
    url: "/profile",
  },
  {
    id: 4,
    name: "Dash",
    avatar: "/images/artists/artist-4.jpg",
    sale: "12.29 ETH",
    crypto: "5 ETH",
    price: "$15,000",
    url: "/profile",
  },
  {
    id: 5,
    name: "Moyo Shiro",
    avatar: "/images/artists/artist-5.jpg",
    sale: "5.66 ETH",
    crypto: "8 ETH",
    price: "$22,111",
    url: "/profile",
  },
  {
    id: 6,
    name: "Dash",
    avatar: "/images/artists/artist-1.jpg",
    sale: "5.244 ETH",
    crypto: "12 ETH",
    price: "$24,550",
    url: "/profile",
  },
  {
    id: 7,
    name: "Foxies",
    avatar: "/images/artists/artist-2.jpg",
    sale: "12.29 ETH",
    crypto: "5 ETH",
    price: "$15,000",
    url: "/profile",
  },
  {
    id: 8,
    name: "Kohaku",
    avatar: "/images/artists/artist-3.jpg",
    sale: "8.13 ETH",
    crypto: "3.2 ETH",
    price: "$9,344",
    url: "/profile",
  },
  {
    id: 9,
    name: "Dash",
    avatar: "/images/artists/artist-4.jpg",
    sale: "12.29 ETH",
    crypto: "5 ETH",
    price: "$15,000",
    url: "/profile",
  },
  {
    id: 10,
    name: "Moyo Shiro",
    avatar: "/images/artists/artist-5.jpg",
    sale: "5.66 ETH",
    crypto: "8 ETH",
    price: "$22,111",
    url: "/profile",
  },
  {
    id: 11,
    name: "Dash",
    avatar: "/images/artists/artist-1.jpg",
    sale: "5.244 ETH",
    crypto: "12 ETH",
    price: "$24,550",
    url: "/profile",
  },
  {
    id: 12,
    name: "Foxies",
    avatar: "/images/artists/artist-2.jpg",
    sale: "12.29 ETH",
    crypto: "5 ETH",
    price: "$15,000",
    url: "/profile",
  },
  {
    id: 13,
    name: "Kohaku",
    avatar: "/images/artists/artist-3.jpg",
    sale: "8.13 ETH",
    crypto: "3.2 ETH",
    price: "$9,344",
    url: "/profile",
  },
  {
    id: 14,
    name: "Dash",
    avatar: "/images/artists/artist-4.jpg",
    sale: "12.29 ETH",
    crypto: "5 ETH",
    price: "$15,000",
    url: "/profile",
  },
  {
    id: 15,
    name: "Moyo Shiro",
    avatar: "/images/artists/artist-5.jpg",
    sale: "5.66 ETH",
    crypto: "8 ETH",
    price: "$22,111",
    url: "/profile",
  },
];

export const seedArtistsWeek = async () => {
  await seedTable(artistsWeek, data, artistsWeek.id);
};
