import { ActivityCollections } from "database/type";
import { seedTable } from "./seedTable";
import { activityCollections } from "database/schema";

const data: ActivityCollections[] = [
  {
    id: 1,
    title: "Cute Robot",
    login: "tranmautritam",
    price: "1.0 ETH",
    avatar: "/images/artists/artist-1.jpg",
    images: [
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-2.jpg",
      "/images/collection/photo-3.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-2.jpg",
      "/images/collection/photo-3.jpg",
      "/images/collection/photo-1.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 2,
    title: "Cute Planet",
    login: "moyoshiro",
    price: "2.8 ETH",
    avatar: "/images/artists/artist-2.jpg",
    images: [
      "/images/collection/photo-4.jpg",
      "/images/collection/photo-5.jpg",
      "/images/collection/photo-6.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-2.jpg",
      "/images/collection/photo-3.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-4.jpg",
      "/images/collection/photo-5.jpg",
      "/images/collection/photo-6.jpg",
      "/images/collection/photo-1.jpg",
    ],
    color: "#B9A9FB",
    url: "/collection",
  },
  {
    id: 3,
    title: "Cute Planet",
    login: "kohaku",
    price: "4.9 ETH",
    avatar: "/images/artists/artist-3.jpg",
    images: [
      "/images/collection/photo-7.jpg",
      "/images/collection/photo-8.jpg",
      "/images/collection/photo-9.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-2.jpg",
      "/images/collection/photo-3.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-7.jpg",
      "/images/collection/photo-8.jpg",
      "/images/collection/photo-9.jpg",
      "/images/collection/photo-7.jpg",
      "/images/collection/photo-8.jpg",
      "/images/collection/photo-9.jpg",
      "/images/collection/photo-7.jpg",
      "/images/collection/photo-8.jpg",
      "/images/collection/photo-9.jpg",
    ],
    color: "#DBFF73",
    url: "/collection",
  },
  {
    id: 4,
    title: "Cute Planet",
    login: "moyoshiro",
    price: "0.3 ETH",
    avatar: "/images/artists/artist-4.jpg",
    images: [
      "/images/collection/photo-10.jpg",
      "/images/collection/photo-11.jpg",
      "/images/collection/photo-12.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-6.jpg",
      "/images/collection/photo-1.jpg",
    ],
    color: "#FFA6D6",
    url: "/collection",
  },
  {
    id: 5,
    title: "Cute Robot",
    login: "tranmautritam",
    price: "1.0 ETH",
    avatar: "/images/artists/artist-5.jpg",
    images: [
      "/images/collection/photo-13.jpg",
      "/images/collection/photo-14.jpg",
      "/images/collection/photo-15.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-2.jpg",
      "/images/collection/photo-3.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-13.jpg",
      "/images/collection/photo-14.jpg",
      "/images/collection/photo-15.jpg",
      "/images/collection/photo-1.jpg",
    ],
    color: "#BCE6EC",
    url: "/collection",
  },
  {
    id: 6,
    title: "Cute Planet",
    login: "randomdash",
    price: "14.5 ETH",
    avatar: "/images/artists/artist-6.jpg",
    images: [
      "/images/collection/photo-16.jpg",
      "/images/collection/photo-17.jpg",
      "/images/collection/photo-18.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-3.jpg",
      "/images/collection/photo-1.jpg",
      "/images/collection/photo-5.jpg",
      "/images/collection/photo-1.jpg",
    ],
    color: "#B9A9FB",
    url: "/collection",
  },
];

export const seedActivityCollections = async () => {
  await seedTable(activityCollections, data, activityCollections.id);
};
